### ISSUE TITLE
DSpace 7 compatibility?

### ISSUE THREAD

**Issue by nwoodward** [ilri/dspace-statistics-api#18]
I'm curious if you've had any chance to test some of your Solr queries on a DSpace 7 instance? So far, I've tried only a few of the example views and downloads queries from the documentation (https://wiki.lyrasis.org/display/DSPACE/Solr). But they either aren't returning any results or they return results that don't make sense.

**Comment by alanorth** [comment]
Hey @nwoodward. I've only done minimal testing with DSpace 7 Solr so far, but I also get the feeling that something is not quite the same. Hoping to look into it more for this dspace-statistics-api soon as we start getting more serious about moving to DSpace 7.

**Comment by nwoodward** [comment]
OK, cool. My sense is that _most_ queries will be about the same, like those for views and downloads. But at least the results that deal with number of items submitted don't look right to me.

**Comment by alanorth** [comment]
FYI I'm running this on DSpace 7.6 now. Our test instance is public:

- https://dspace7test.ilri.org/rest/statistics

I have not made a DSpace 7 branch in this repo yet because I'm using the 6_x branch without modifications.
